version: '3.8'
services:
  cbr-rate:
    image: cbr-rate
    build:
      context: C:/Users/nikim/currency-rate/cbr-rate
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://currency-db:5432/currency-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - "8980:8980"
    depends_on:
      - currency-db

  currency-calculation:
    image: currency-calculation
    build:
      context: C:/Users/nikim/currency-rate/currency-calculation
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://calculation-db:5432/currency-calculation-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - GRPC_CLIENT_GLOBAL_ADDRESS=static://cbr-rate:8980
    ports:
      - "8081:8081"
    depends_on:
      - calculation-db
      - cbr-rate

  currency-db:
    image: postgres:13
    environment:
      POSTGRES_DB: currency-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5432:5432"

  calculation-db:
    image: postgres:13
    environment:
      POSTGRES_DB: currency-calculation-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5433:5432"

  currency-frontend:
    build:
      context: C:/Users/nikim/currency-rate/currency-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - currency-calculation