version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: currency-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cbr-rate:
    build:
      context: C:/Users/nikim/currency-rate/cbr-rate
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/currency-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql
    depends_on:
      - postgres
    ports:
      - "8082:8082"

  currency-calculation:
    build:
      context: C:/Users/nikim/currency-rate/currency-calculation
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/currency-calculation-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql
      - GRPC_CLIENT_CBR-RATE_ADDRESS=cbr-rate:localhost:8980
    depends_on:
      - postgres
      - cbr-rate
    ports:
      - "8081:8081"

volumes:
  pgdata: