server:
  port: 8081

grpc:
  client:
    GLOBAL:
      address: "static://localhost:8980"
      negotiation-type: plaintext

spring:
  spring:
    codec:
      charset: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/currency-calculation-db
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: currency-calculation-service

logging:
  level:
    ru.mycompany: INFO
  charset: UTF-8

